#!/bin/bash

echo "=== Browser Testing Guide ==="
echo ""
echo "Server: http://127.0.0.1:8080"
echo ""

echo "Test Cases:"
echo ""
echo "1. Load Wizard"
echo "   URL: http://127.0.0.1:8080"
echo "   Expected: Redirect to /wizard/1"
echo ""

echo "2. Screen 1 - URL Input"
echo "   URL: http://127.0.0.1:8080/wizard/1"
echo "   Expected: Shows URL input form"
echo "   Test:"
echo "   - Enter 'invalid-url' → Should show error"
echo "   - Enter 'example.com' → Should accept"
echo "   - Enter 'https://google.com' → Should accept"
echo ""

echo "3. Screen 2 - Branding"
echo "   URL: http://127.0.0.1:8080/wizard/2"
echo "   Expected: Shows branding form"
echo "   Test:"
echo "   - Enter App Name: 'Test App'"
echo "   - Choose Color: '#FF5733'"
echo "   - Leave Logo empty"
echo "   - Click Save → Should show success"
echo ""

echo "4. Persistence Test"
echo "   - Close browser"
echo "   - Reopen http://127.0.0.1:8080"
echo "   - Should resume at Step 2"
echo ""

echo "5. HTMX Test"
echo "   - On Screen 1, type URL"
echo "   - Should validate without page reload"
echo "   - Should show inline validation"
echo ""

echo "6. Alpine.js Test"
echo "   - On Screen 2, change color"
echo "   - Should update preview instantly"
echo ""

echo "7. Responsive Test"
echo "   - Resize browser to mobile width"
echo "   - Layout should adapt"
echo ""

echo "8. Offline Test"
echo "   - All assets should load from local server"
echo "   - No external requests should be made"
echo "   - Check DevTools Network tab"
echo ""
