name: Capacitor Sync
description: Build web assets and sync Capacitor

runs:
  using: composite
  steps:
    - name: Install Dependencies
      run: npm ci
      shell: bash

    - name: Build Web Assets
      run: npm run build
      shell: bash

    - name: Sync Capacitor Android
      run: npx cap sync android
      shell: bash
