package generator

import (
    "encoding/json"
    "fmt"
    "net/url"
)

type CapacitorConfig struct {
    AppID           string         `json:"appId"`
    AppName         string         `json:"appName"`
    WebDir          string         `json:"webDir"`
    BackgroundColor string         `json:"backgroundColor,omitempty"`
    Server          ServerConfig   `json:"server,omitempty"`
    Android         AndroidConfig  `json:"android,omitempty"`
    IOS             IOSConfig      `json:"ios,omitempty"`
}

type ServerConfig struct {
    AndroidScheme   string   `json:"androidScheme,omitempty"`
    Cleartext       bool     `json:"cleartext,omitempty"`
    AllowNavigation []string `json:"allowNavigation,omitempty"`
}

type AndroidConfig struct {
    AllowMixedContent bool `json:"allowMixedContent,omitempty"`
}

type IOSConfig struct {
    ContentInset string `json:"contentInset,omitempty"`
}

func (g *Generator) GenerateCapacitorConfig() (string, error) {
    // Use a fixed package name to avoid Android 16's "new package" restriction
    // on side-loaded apps. All projects share the same package.
    appID := fmt.Sprintf("com.kinbuilder.app%d", g.project.ID)
    // Use a fixed package name to avoid conflicts with previous installs
    // appID = fmt.Sprintf("com.localapkbuilder.app%d.v%s", g.project.ID, strings.ReplaceAll(g.project.Version, ".", ""))
    hostname := extractHostname(g.project.URL)
    bgColor := g.project.PrimaryColor
    if g.project.SplashConfig != "" {
        var splash struct {
            BackgroundColor string `json:"background_color"`
        }
        if err := json.Unmarshal([]byte(g.project.SplashConfig), &splash); err == nil && splash.BackgroundColor != "" {
            bgColor = splash.BackgroundColor
        }
    }

    cfg := CapacitorConfig{
        AppID:           appID,
        AppName:         g.project.AppName,
        WebDir:          "www",
        BackgroundColor: bgColor,
        Server: ServerConfig{
            AndroidScheme:   "https",
            Cleartext:       true,
            AllowNavigation: []string{hostname, "cdn.tailwindcss.com", "cdnjs.cloudflare.com", "fonts.googleapis.com", "fonts.gstatic.com"},
        },
        Android: AndroidConfig{
            AllowMixedContent: true,
        },
        IOS: IOSConfig{
            ContentInset: "always",
        },
    }
    data, err := json.MarshalIndent(cfg, "", "  ")
    if err != nil {
        return "", err
    }
    return string(data), nil
}

func (g *Generator) GeneratePackageJSON() (string, error) {
    deps := GetPluginDependencies(g.project.FeaturesConfig)
    pkg := map[string]interface{}{
        "name":         g.project.AppName,
        "version":      g.project.Version,
        "description":  "Generated by Local APK Builder",
        "private":      true,
        "dependencies": deps,
        "devDependencies": map[string]string{
            "@capacitor/assets": "^3.0.5",
        },
    }
    data, err := json.MarshalIndent(pkg, "", "  ")
    if err != nil {
        return "", err
    }
    return string(data), nil
}

func extractHostname(urlStr string) string {
    u, err := url.Parse(urlStr)
    if err != nil || u.Host == "" {
        return "*"
    }
    return u.Hostname()
}
